language: go

go:
  - 1.9.x
  - master

sudo: required
services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  # Download and install dep
  - curl -sI https://github.com/golang/dep/releases/latest | grep -Fi Location  | tr -d '\r' | sed "s/tag/download/g" | awk -F " " '{ print $2 "/dep-linux-amd64"}' | wget --output-document=$GOPATH/bin/dep -i -
  - chmod +x $GOPATH/bin/dep
  # Install linters and misspell
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  # Install latest docker image
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
    # FIXME(#46924): these two commands are required to enable IPv6,
  # they shouldn't exist, please revert once more official solutions appeared.
  # see https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729
  - if [ "$TRAVIS_OS_NAME" = linux ]; then
      echo '{"ipv6":true,"fixed-cidr-v6":"fe80::/64"}' | sudo tee /etc/docker/daemon.json;
      sudo service docker restart;
    fi
  - docker volume prune -f

install: make dependencies


stages:
  - build
  - test
  - name: integration-tests
    if: $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$

jobs:
  include:
    - stage: integration-tests
      script: chmod +x /integration/docker/build.sh && ./integration/docker/build.sh && make integration-tests
